# Generated by Django 3.1.3 on 2020-11-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('sigungu', models.CharField(max_length=30)),
                ('dong', models.CharField(blank=True, max_length=30)),
                ('ri', models.CharField(blank=True, max_length=20)),
                ('doro', models.CharField(max_length=50)),
                ('detail', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
