# Generated by Django 3.0.8 on 2020-11-12 19:28

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_big', models.CharField(choices=[('vege', '채소'), ('fruit', '과일'), ('else', '기타')], max_length=10)),
                ('kind_small_vege', models.CharField(blank=True, choices=[('potato', '감자'), ('union', '양파'), ('carrot', '당근'), ('sweetp', '고구마')], max_length=10)),
                ('kind_small_fruit', models.CharField(blank=True, choices=[('apple', '사과'), ('tomato', '토마토'), ('banana', '바나나'), ('pear', '배')], max_length=10)),
                ('kind_small_else', models.CharField(blank=True, choices=[('amu', '아무'), ('nothing', '무엇')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=200)),
                ('main_image', models.ImageField(upload_to='')),
                ('open', models.BooleanField()),
                ('price', models.IntegerField()),
                ('weight', models.FloatField()),
                ('stock', models.IntegerField()),
                ('instruction', models.TextField(blank=True)),
                ('desc', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('preparing', '배송 준비 중'), ('shipping', '배송 중\x1d'), ('complete', '완료')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('purchase_datetime', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=models.SET(products.models.get_delete_product), to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
